### PR TITLE
Remove unnecessary requirements and allow more Sylius versions

### PR DESCRIPTION
**Pull request by Prometee**
Related issue #116 

- [x] Allow Sylius 1.12 and futur releases
- [x] Add Sylius 1.12 to GitHub Action
- [x] Switch test app to Webpack

### CODE REVIEW

**Comment by Prometee** [comment]
@mamazu my GitHub action are always failing on BeHat tests for apparently no reason or not one I can't explain yet, but I tested it locally with Sylius 1.11 and Sylius 1.12.x-dev and there is no error at all.

**Comment by Prometee** [comment]
@mamazu nail it, my local folder `tests/Application/public/build` wasn't flush between each of my tests, and that's why I haven't seen the entry point error I had, now the build is running green : https://github.com/Prometee/SyliusCustomOptionsPlugin/actions/runs/3298832922

**Comment by mamazu** [comment]
Sorry for the late reply, thank you very much for all the work of upgrading the plugin. I will merge and tag it.

**Comment by Prometee** [comment]
@mamazu no problem it was quick enough 😉
I needed it also to tests my own plugin so this work on Sylius 1.12 will be reused.

**Pull request merged**
