### PR TITLE
Update doctrine configuration

### PR DESCRIPTION
**Pull request by JoppeDC**
This PR References issue https://github.com/Brille24/SyliusCustomOptionsPlugin/issues/148

- The doctrine XML config has been moved to attributes
- The custom migrations have been removed from the bundle. These should be generated in the project itself

Note:
The overwriting of the Sylius resources has also been removed. The test application should probably be updated to reflect the newer way of working

Feedback is appreciated

### CODE REVIEW

**Comment by JoppeDC** [comment]
I have updated the Readme to reflect the changes in regards to migrations. I've also added a small UPGRADE doc, documenting the changes to the migrations and ORM mapping.

Please feel free to let me know if you have any more changes you'd like to see!

**Comment by mamazu** [comment]
Perfect. I think this would probably be tagged as 4.0 then as this is a BC break.

I'm not sure if that's going to play well with other projects still using XML (and wanting to use this package). Is this possible? I'll do some testing in our Sylius project to see if it still works.

**Comment by JoppeDC** [comment]
Unfortunatly i do not currently have a project that uses XML mapping, although this should not be a problem.

**Comment by mamazu** [comment]
Anything else that's needs to be done? Otherwise I'd merge it and tag it as the new version.

**Comment by JoppeDC** [comment]
I'm currently using it pinned on my fork branch, and during my testing it has been working fine.

Maybe a rename of the UPGRADE markdown file based on the tag you're planning to push?

**Comment by mamazu** [comment]
Sure, that would be great.  It's planned as 4.0

**Comment by JoppeDC** [comment]
Awesome, i've updated the readme @mamazu

**Comment by mamazu** [comment]
Thanks for your contribution. :tada:

**Pull request merged**
